// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $bagPage from "./routes/bagPage.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $productPage_id_ from "./routes/productPage/[id].tsx";
import * as $productsPage from "./routes/productsPage.tsx";
import * as $AddToCart from "./islands/AddToCart.tsx";
import * as $BagPage from "./islands/BagPage.tsx";
import * as $CartProvider from "./islands/CartProvider.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $search_bar from "./islands/search-bar.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/bagPage.tsx": $bagPage,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/productPage/[id].tsx": $productPage_id_,
    "./routes/productsPage.tsx": $productsPage,
  },
  islands: {
    "./islands/AddToCart.tsx": $AddToCart,
    "./islands/BagPage.tsx": $BagPage,
    "./islands/CartProvider.tsx": $CartProvider,
    "./islands/Counter.tsx": $Counter,
    "./islands/search-bar.tsx": $search_bar,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
